name: git-auto-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}

    - name: Use git-auto-commit-action
      id: "auto-commit-action"
      uses: ./

    - name: "no changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: "echo \"No changes detected\""

    - name: "changes detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: "echo \"Changes detected\""
